### ISSUE TITLE
In the VSCode extension: Add `(simulator)` to the displayed device name in the device list, if it is a simulator

### ISSUE THREAD

**Issue by HelenaMeyer** [toitware/ide-tools#161]
In the Toit console, the device name has a `(simulator)` added to the device name if the device is a simulator, in order to get a quick overview of which devices are simulators and which are not:

![Screenshot from 2021-12-01 11-57-47](https://user-images.githubusercontent.com/19826501/144222524-c17bb6b6-f646-4783-ad73-b712803a7b12.png)

In the VSCode extension, the same could be nice to have..
![Screenshot from 2021-12-01 11-56-59](https://user-images.githubusercontent.com/19826501/144222672-a86ad48d-a5fc-4e36-ae58-afcee7eeeb43.png)

**Comment by floitsch** [comment]
Simulators aren't supported anymore.
Closing.
