### ISSUE TITLE
The `toit` executable at '/Users/UserName/Applications' was found but did not execute correctly.

### ISSUE THREAD

**Issue by krzychb** [toitware/ide-tools#165]
Hi, I am getting this error message when opening the folder with toit applications from VS Code on MacBook Pro (Mojave ver. 10.14.6):
![image](https://user-images.githubusercontent.com/12953787/144569259-3888df34-fe99-4646-9bbc-cfad7629a63d.png)

Running toit from the command line does not show any errors and I am able to load applications to devices.
How to troubleshoot this issue?

**Comment by lask** [comment]
Thanks for submitting the issue. Have you set the `toit` path in the extension settings? If so, you can try to remove it (or set it to null), then the extension will just look in your `PATH` for `toit`.

If you need to set the path in the extension setting, then I think it should be the full path for the executable, e.g. `/Users/krzysztof/Applications/toit`.

Let me know if any of this works for you.

**Comment by krzychb** [comment]
Yes. Setting the full path works (I missed the `/toit` bit). Thank you @lask!
