### ISSUE TITLE
log in failed

### ISSUE THREAD

**Issue by lin961210** [toitware/ide-tools#169]
When I want to compile a program, the VS Code plug-in prompts me to log in and then jumps to the login page of the web page. The web page prompts me to log in successfully, but the VS Code prompts me not to log in successfully.
![image](https://user-images.githubusercontent.com/96114220/145976879-8e527b62-1c98-464d-ada8-977ae6d17b2a.png)
![image](https://user-images.githubusercontent.com/96114220/145976940-3c0d186b-88d5-45bf-9e93-5935f5f048d6.png)

**Comment by floitsch** [comment]
Sorry for the late reply.
If you still see this issue, please reopen or contact us on github.com/toitlang/toit/discussions or through one of our chats.
