### ISSUE TITLE
Where do I find `jag` actions?

### ISSUE THREAD

**Issue by kasperl** [toitware/ide-tools#185]
I'm running 1.4.0 of the VS Code extension and I've got `jag`, but not `toit` installed. The LSP integration is working, but I cannot find the `jag` specific file actions (run, watch, etc.).

**Comment by lask** [comment]
The `jag` commands are implemented as [commands](https://code.visualstudio.com/api/extension-guides/command), and they are accessible from the [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette). Press `Ctrl+Shift+P` to access the command palette and type `Jaguar` to see the commands.
![image](https://user-images.githubusercontent.com/5364453/148024674-e179861b-5783-46b7-a05f-75f2f8b7e7ed.png)
Note: The extension is only active when there is a `.toit` file in your workspace.
