### ISSUE TITLE
extension don't activate

### ISSUE THREAD

**Issue by mess-maker** [toitware/ide-tools#191]
hi,

Can't manage to get the extension to activate

I have setup jag with latest version
```
PS C:\Users\mess-maker> jag version
Version:         v0.8.0
SDK version:     v0.16.0
Build date:      2022-01-31T13:14:30Z
```
jag.exe is on $PATH

do I need to set anything else to have the extension activate ?
for now when I open a .toit file I get `TypeError: Cannot read property 'uri' of undefined` error message from the extension

**Comment by floitsch** [comment]
This was a bug on Windows and is fixed in the latest release.
