### ISSUE TITLE
CLI single sign on not working

### ISSUE THREAD

**Issue by AdriaanBurger** [toitware/ide-tools#199]
When I try to access my devices via the Toit CLI it prompts me to sign in. I enter my credentials and get redirected to a localhost page which fails. 
![image](https://user-images.githubusercontent.com/78842420/157835177-264e4f8b-10eb-4df9-972b-f7789ef98b91.png)
o load.
![image](https://user-images.githubusercontent.com/78842420/157835338-ba8765b0-6aa0-4cc8-9a01-f21dfc4050c3.png)
![image](https://user-images.githubusercontent.com/78842420/157835508-dd6e18fe-b4a9-4e25-a333-47be65304480.png)
![image](https://user-images.githubusercontent.com/78842420/157835600-9de35fa6-6998-41ad-8990-5cb2a0ad0c05.png)

**Comment by floitsch** [comment]
Do you maybe have two different accounts?
If the config file thinks that you are one user, but you sign in with a different one, then things don't work correctly.
I believe you get the error message you see here.

I think the easiest is to (re)move the existing configuration file in that case.

**Comment by AdriaanBurger** [comment]
I do not have more than one user account. I have ensured that there is only one instance in my configuration. Removed/recreated the config file. Manually set the paths to the CLI as well because VSCode does not pick up toit installation although it is found on my system using "where toit". Still no luck

**Comment by floitsch** [comment]
Any chance the connection is blocked by a firewall?

**Comment by floitsch** [comment]
Investigated a bit more: normally the oauth connects to a local http (not https) connection.
However, in your case it seems like it wants to connect with https (thus giving an "ERR_SSL_PROTOCOL_ERROR").
There seems to be something that tries to upgrade the connection from http to https, even though we are working on the same computer (localhost).

Which browser/version are you using?
Do you have any extension that could do this?

**Comment by AdriaanBurger** [comment]
I have disable my firewall and added rules to allow all ports for inbound and outbound, as well as the program. Still no luck.

**Comment by floitsch** [comment]
Apparently there is a sticky flag in Chrome that auto-upgrades connections once they have been upgraded once.

Have a look at chrome://net-internals/#hsts and query "localhost", to see if there is some information.
If yes, delete the domain security policies for it. (Normally there isn't one for localhost).

https://stackoverflow.com/questions/25277457/google-chrome-redirecting-localhost-to-https

**Comment by AdriaanBurger** [comment]
Hi. That worked for me. Thank you very much.
