### ISSUE TITLE
constant `as` cant match

### ISSUE THREAD

**Issue by RedCMD** [toitware/ide-tools#246]
The regex for `as`
`\b(?<!)as(?!-)\b` is missing `-` inside `(?<!)` => `(?<!-)`
`(?<!)` will never match

https://github.com/toitware/ide-tools/blob/60efd96a42cd639f7c966d9ed51b1cd456e4a8e8/vscode/syntaxes/toit.tmLanguage.yaml#L47

**Comment by floitsch** [comment]
Big thanks for filing these issues.
Pull requests are uploaded.
